/**
 * UperLevel desktop capture agent.
 *
 * Hostname-mapped, not per-employee login: the machine's own OS hostname
 * is sent with every capture, and the Laravel side maps that hostname to
 * an employee (Company -> HR -> Employees -> "Workstation machine name").
 *
 * Runs a visible tray icon at all times — this agent is deliberately NOT
 * hidden or silent-by-design. Errors are logged (console + agent.log) and
 * swallowed so a transient network blip never crashes the process, but
 * that is graceful error handling, not concealment: the tray icon stays
 * present and inspectable the whole time the agent is running.
 */

'use strict';

require('dotenv').config();

const fs = require('fs');
const os = require('os');
const path = require('path');
const axios = require('axios');
const cron = require('node-cron');
const screenshot = require('screenshot-desktop');
const SysTray = require('systray2').default;

// ---- Configuration ---------------------------------------------------

const API_URL = process.env.API_URL || 'http://127.0.0.1:8000';
const AGENT_SECRET = process.env.AGENT_SECRET || '';
const CAPTURE_INTERVAL_MINUTES = Math.max(1, parseInt(process.env.CAPTURE_INTERVAL_MINUTES, 10) || 5);
const MACHINE_NAME = process.env.MACHINE_NAME_OVERRIDE || os.hostname();
const CAPTURE_ENDPOINT = `${API_URL.replace(/\/+$/, '')}/api/v1/agent/capture`;
const LOG_FILE = path.join(__dirname, 'agent.log');

// ---- Logging (console + local file, never throws) ---------------------

function log(level, message) {
    const line = `[${new Date().toISOString()}] [${level}] ${message}`;
    // eslint-disable-next-line no-console
    console[level === 'ERROR' ? 'error' : 'log'](line);
    try {
        fs.appendFileSync(LOG_FILE, line + '\n');
    } catch {
        // If even local logging fails (e.g. read-only disk), there's
        // nothing safe left to do but keep the process alive.
    }
}

// ---- Capture + upload ---------------------------------------------------

async function captureAndUpload() {
    let imageBuffer;

    try {
        imageBuffer = await screenshot({ format: 'jpg' });
    } catch (err) {
        log('ERROR', `Screenshot capture failed: ${err.message}`);
        return;
    }

    try {
        await axios.post(
            CAPTURE_ENDPOINT,
            {
                machine_name: MACHINE_NAME,
                image: imageBuffer.toString('base64'),
                captured_at: new Date().toISOString(),
            },
            {
                headers: {
                    'Content-Type': 'application/json',
                    'X-Agent-Secret': AGENT_SECRET,
                },
                timeout: 15000,
                maxBodyLength: 25 * 1024 * 1024,
            }
        );
        log('INFO', `Capture uploaded (${MACHINE_NAME}, ${Math.round(imageBuffer.length / 1024)}KB).`);
    } catch (err) {
        const status = err.response ? err.response.status : 'network error';
        log('ERROR', `Upload failed (${status}): ${err.message}`);
        // Deliberately swallowed — a missed capture or a down server
        // should never crash the agent or interrupt the tray icon.
    }
}

// ---- Scheduling -----------------------------------------------------------

const cronExpression = `*/${CAPTURE_INTERVAL_MINUTES} * * * *`;
log('INFO', `UperLevel capture agent starting — machine "${MACHINE_NAME}", every ${CAPTURE_INTERVAL_MINUTES} min, target ${CAPTURE_ENDPOINT}`);

if (!AGENT_SECRET) {
    log('ERROR', 'AGENT_SECRET is not set — captures will be rejected if the server requires one. Copy .env.example to .env and fill it in.');
}

cron.schedule(cronExpression, () => {
    captureAndUpload().catch((err) => log('ERROR', `Unexpected error in scheduled capture: ${err.message}`));
});

// ---- Tray icon (visible presence — required, not optional) ---------------

let systray;

function startTray() {
    // systray2's `icon` field is a FILE PATH it reads and encodes itself,
    // not a pre-encoded base64 string — and Windows specifically needs
    // .ico (a .png there can fail to render even though the process stays
    // up). assets/icon.ico and assets/icon.png are both generated by this
    // project; swap in your own branding by replacing those two files.
    const iconPath = path.join(__dirname, 'assets', os.platform() === 'win32' ? 'icon.ico' : 'icon.png');

    const captureNowItem = {
        title: 'Capture now',
        tooltip: 'Trigger an immediate capture',
        checked: false,
        enabled: true,
        click: () => captureAndUpload().catch((err) => log('ERROR', `Manual capture failed: ${err.message}`)),
    };
    const openLogItem = {
        title: 'Open agent.log',
        tooltip: '',
        checked: false,
        enabled: true,
        click: () => require('child_process').exec(`start "" "${LOG_FILE}"`, () => {}),
    };
    const quitItem = {
        title: 'Quit',
        tooltip: '',
        checked: false,
        enabled: true,
        click: () => shutdown(),
    };

    systray = new SysTray({
        menu: {
            icon: iconPath,
            title: 'UperLevel Monitor',
            tooltip: `UperLevel Monitor — active (${MACHINE_NAME})`,
            items: [
                { title: `Active — capturing every ${CAPTURE_INTERVAL_MINUTES} min`, tooltip: '', checked: false, enabled: false },
                { title: `Machine: ${MACHINE_NAME}`, tooltip: '', checked: false, enabled: false },
                SysTray.separator,
                captureNowItem,
                openLogItem,
                quitItem,
            ],
        },
        debug: false,
        copyDir: true,
    });

    systray.onError((err) => log('ERROR', `Tray process error: ${err.message}`));
}

function shutdown() {
    log('INFO', 'UperLevel capture agent shutting down.');
    try {
        if (systray) systray.kill();
    } finally {
        process.exit(0);
    }
}

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);
process.on('uncaughtException', (err) => log('ERROR', `Uncaught exception (agent kept running): ${err.stack || err.message}`));
process.on('unhandledRejection', (reason) => log('ERROR', `Unhandled rejection (agent kept running): ${reason}`));

try {
    startTray();
} catch (err) {
    // A tray-icon failure (e.g. missing native dependency on this OS)
    // must not silently hide the agent — fall back to a visible console
    // process instead of disappearing.
    log('ERROR', `Tray icon failed to start (${err.message}) — agent is still running in this console window.`);
}

// Fire one capture shortly after startup so the admin doesn't wait a full
// interval to confirm the agent is actually working.
setTimeout(() => {
    captureAndUpload().catch((err) => log('ERROR', `Startup capture failed: ${err.message}`));
}, 5000);
