<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{{ $title }}</title>
<style>
    * { box-sizing: border-box; }
    body { font-family: 'DejaVu Sans', Helvetica, Arial, sans-serif; color:#1A1A1A; font-size:11px; margin:0; padding:0; }
    .doc-wrap { padding: 24px 28px; }
    .doc-header { width:100%; border-bottom:3px solid #2D6A4F; padding-bottom:14px; margin-bottom:18px; }
    .doc-header table { width:100%; border-collapse:collapse; }
    .doc-header td { vertical-align:top; }
    .company-name { font-size:19px; font-weight:bold; color:#2D6A4F; }
    .company-sub { font-size:10px; color:#777; margin-top:2px; }
    .report-title { font-size:16px; font-weight:bold; text-align:right; color:#1A1A1A; }
    .report-meta { font-size:9.5px; color:#777; text-align:right; margin-top:4px; line-height:1.5; }
    table.data { width:100%; border-collapse:collapse; margin-top:6px; }
    table.data th { background:#2D6A4F; color:#fff; text-align:left; padding:7px 9px; font-size:9.5px; text-transform:uppercase; letter-spacing:.03em; }
    table.data td { padding:6px 9px; border-bottom:1px solid #E2E2E2; font-size:10.5px; }
    table.data tr:nth-child(even) td { background:#F7F9F8; }
    .doc-footer { margin-top:22px; padding-top:10px; border-top:1px solid #DDD; font-size:9px; color:#999; text-align:center; }
    .empty-note { text-align:center; color:#999; padding:24px; }
</style>
</head>
<body>
    <div class="doc-wrap">
        <div class="doc-header">
            <table>
                <tr>
                    <td>
                        <div class="company-name">{{ $companyName }}</div>
                        <div class="company-sub">Powered by UperLevel</div>
                    </td>
                    <td style="text-align:right;">
                        <div class="report-title">{{ $title }}</div>
                        <div class="report-meta">
                            {{ $subtitle }}<br>
                            Generated {{ $generatedAt }} by {{ $generatedBy }}
                        </div>
                    </td>
                </tr>
            </table>
        </div>

        <table class="data">
            <tr>
                @foreach ($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr><td class="empty-note" colspan="{{ count($headers) }}">No data for this selection.</td></tr>
            @endforelse
        </table>

        <div class="doc-footer">
            {{ $companyName }} — Confidential — Generated by UperLevel
        </div>
    </div>

    @if (($mode ?? 'pdf') === 'print')
        <script>window.onload = function () { window.print(); };</script>
    @endif
</body>
</html>
