<?php

// ISO 4217 code => display name + symbol. Single source of truth for the
// base-currency dropdown and every "dynamic symbol" lookup (Finance Setup,
// bank accounts, invoices) — see FinanceSettings::currencySymbol().
return [
    'USD' => ['name' => 'US Dollar', 'symbol' => '$'],
    'EUR' => ['name' => 'Euro', 'symbol' => '€'],
    'GBP' => ['name' => 'British Pound', 'symbol' => '£'],
    'PKR' => ['name' => 'Pakistani Rupee', 'symbol' => '₨'],
    'INR' => ['name' => 'Indian Rupee', 'symbol' => '₹'],
    'AED' => ['name' => 'UAE Dirham', 'symbol' => 'د.إ'],
    'SAR' => ['name' => 'Saudi Riyal', 'symbol' => '﷼'],
    'CAD' => ['name' => 'Canadian Dollar', 'symbol' => '$'],
    'AUD' => ['name' => 'Australian Dollar', 'symbol' => '$'],
    'JPY' => ['name' => 'Japanese Yen', 'symbol' => '¥'],
    'CNY' => ['name' => 'Chinese Yuan', 'symbol' => '¥'],
    'CHF' => ['name' => 'Swiss Franc', 'symbol' => 'Fr'],
    'SGD' => ['name' => 'Singapore Dollar', 'symbol' => '$'],
    'HKD' => ['name' => 'Hong Kong Dollar', 'symbol' => '$'],
    'NZD' => ['name' => 'New Zealand Dollar', 'symbol' => '$'],
    'ZAR' => ['name' => 'South African Rand', 'symbol' => 'R'],
    'TRY' => ['name' => 'Turkish Lira', 'symbol' => '₺'],
    'RUB' => ['name' => 'Russian Ruble', 'symbol' => '₽'],
    'BRL' => ['name' => 'Brazilian Real', 'symbol' => 'R$'],
    'MXN' => ['name' => 'Mexican Peso', 'symbol' => '$'],
    'IDR' => ['name' => 'Indonesian Rupiah', 'symbol' => 'Rp'],
    'MYR' => ['name' => 'Malaysian Ringgit', 'symbol' => 'RM'],
    'THB' => ['name' => 'Thai Baht', 'symbol' => '฿'],
    'PHP' => ['name' => 'Philippine Peso', 'symbol' => '₱'],
    'BDT' => ['name' => 'Bangladeshi Taka', 'symbol' => '৳'],
    'EGP' => ['name' => 'Egyptian Pound', 'symbol' => '£'],
    'NGN' => ['name' => 'Nigerian Naira', 'symbol' => '₦'],
    'KES' => ['name' => 'Kenyan Shilling', 'symbol' => 'KSh'],
    'QAR' => ['name' => 'Qatari Riyal', 'symbol' => '﷼'],
    'KWD' => ['name' => 'Kuwaiti Dinar', 'symbol' => 'د.ك'],
    'OMR' => ['name' => 'Omani Rial', 'symbol' => '﷼'],
    'BHD' => ['name' => 'Bahraini Dinar', 'symbol' => '.د.ب'],
];
